### ISSUE TITLE
[aaudio/hello-aaudio] leaks a thread in error callback

### ISSUE THREAD

**Issue by philburk** [googlesamples/android-audio-high-performance#103]
The error callback [launches](https://github.com/googlesamples/android-audio-high-performance/blob/master/aaudio/hello-aaudio/src/main/cpp/PlayAudioEngine.cpp#L357) a thread to restart the stream when disconnected.

It creates a thread and stores a pointer in streamRestartThread_, which is never deleted.
Also streamRestartThread_ is never initialized.

I am also concerned that there might be a race condition when the restartStream std::function object goes out of scope.

A better approach might be what we do in Oboe.

```
std::thread t(oboe_aaudio_error_thread_proc, oboeStream, stream, static_cast<Result>(error));
t.detach();
```

**Comment by ggfan** [comment]
let me have a look at it.
