### ISSUE TITLE
AudioManager set MODE_IN_COMMUNICATION mode cause AAUDIO_ERROR_DISCONNECTED 

### ISSUE THREAD

**Issue by Piasy** [googlesamples/android-audio-high-performance#115]
Add code below to [Echo sample MainActivity startEchoing method](https://github.com/googlesamples/android-audio-high-performance/blob/master/aaudio/echo/src/main/java/com/google/sample/aaudio/echo/MainActivity.java#L117) could reproduce it:

``` java
AudioManager audioManager = ((AudioManager) getApplicationContext()
        .getSystemService(Context.AUDIO_SERVICE));
audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
```

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
