### ISSUE TITLE
add oboe echo to retire all other echo samples

### ISSUE THREAD

**Issue by ggfan** [googlesamples/android-audio-high-performance#116]
Still getting questions about the OpenSL ES echo sample, we probably need to consolidate it to use Oboe interface, what do you think?

background: https://github.com/googlesamples/android-ndk/issues/526

**Comment by dturner** [comment]
Agree. I think it's worth leaving the echo sample in case someone needs to use OpenSL ES directly (e.g. if they're writing their own middleware) but directing most users to a new Oboe version makes sense. 

Fancy writing it? It's been on my TODO list for months but haven't got round to yet.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
