### ISSUE TITLE
new logo / icon

### ISSUE THREAD

**Issue by luthfirangers** [googlesamples/android-audio-high-performance#117]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by dturner** [comment]
Wow, thanks for the offer! Being honest, your help would be much more appreciated on this project https://github.com/google/oboe which is where most of our development effort is focussed at the moment. 

Would that be of interest to you?
