### ISSUE TITLE
SetPitch or SetRate

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-audio-high-performance#118]
Hi,

I want to add SetPitch or SetRate to audio echo project and I can't understand how to use it.
Look at:
https://www.khronos.org/registry/OpenSL-ES/specs/OpenSL_ES_Specification_1.1.pdf

I understood that setPitch are not supported on Android. 

Could you give an example of implementation(not must using OpenSL ES) ?
Could you help ?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
