### ISSUE TITLE
Cannot build SimpleSynth in AndroidStudio

### ISSUE THREAD

**Issue by philburk** [googlesamples/android-audio-high-performance#119]
On an up-to-date AndroidStudio I get these errors when building SimpleSynth

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by ggfan** [comment]
I could have a look at it today.

**Comment by ggfan** [comment]
armeabi/mips was removed with new NDK ( I think from r17 ), update build to new gradle plugin version would fix the issue.  PR is created, please take a look, and I will merge it in. thx

**Comment by dturner** [comment]
Thanks for doing this Gerry!
