### ISSUE TITLE
Running echo on a Mate 20 Pro

### ISSUE THREAD

**Issue by drormaydan** [googlesamples/android-audio-high-performance#123]
Hi,
  I've tried to use the echo sample on a Huawei Mate 20 Pro, and the sound comes out at a much lower frequency and distorted.  Any idea if this bug is in the demo or the phone software?   I was able to run the demo without issue on other Huawei phones.

Thanks!
Dror

**Comment by philburk** [comment]
There may be an issue with the mono input on the Huawei Mate 20 Pro. As an experiment, can you try switching to stereo? You may need to modify the processing code to handle the two channels.

**Comment by philburk** [comment]
Also note that we recommend using Oboe instead of calling AAudio directly.

https://github.com/google/oboe

**Comment by drormaydan** [comment]
Thanks!  The Oboe sample does appear to work properly. Btw, I notice that the LiveEffect app allows me to select telephony as either the input or output device.  Does that mean that if I select telephony as a playback device and make a call at the same time, my call will filter my speech through the App?  I had read previously that Android doesn’t allow you to create a virtual microphone.

Thanks!
Dror

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
