### ISSUE TITLE
i want to add delay in real time playback ... i have  try this . i want to add delay like 2 second , 3 second and so on

### ISSUE THREAD

**Issue by NoumanKashmiri** [googlesamples/android-audio-high-performance#126]
audioManager = (AudioManager) this.getSystemService(Context.AUDIO_SERVICE);
        audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
        audioManager.setSpeakerphoneOn(true);
        requestAudioPermissions();

        (new Thread()
        {
            @Override
            public void run()

            {

                recordAndPlay();

            }
        }).start();

        startButton =  findViewById(R.id.start_button);
        startButton.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                if (!isRecording)
                {
                    initRecordAndTrack();
                    startRecordAndPlay();
                }
            }
        });
        stopButton =  findViewById(R.id.stop_button);

        stopButton.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                    stopRecordAndPlay();
            }
        });
    }

    public void initRecordAndTrack()
    {
       // int min=9000;
        min = AudioRecord.getMinBufferSize(48000, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT);
        audioRecord =new AudioRecord(MediaRecorder.AudioSource.VOICE_COMMUNICATION,16000,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,min);

        if (AcousticEchoCanceler.isAvailable())
        {

            AcousticEchoCanceler  echoCancler = AcousticEchoCanceler.create(audioRecord.getAudioSessionId());
            echoCancler.setEnabled(true);
        }
        int maxJitter = AudioTrack.getMinBufferSize(16000, AudioFormat.CHANNEL_OUT_MONO, AudioFormat.ENCODING_PCM_16BIT);

        audioTrack = new AudioTrack(AudioManager.MODE_IN_COMMUNICATION, 16000, AudioFormat.CHANNEL_OUT_MONO, AudioFormat.ENCODING_PCM_16BIT, maxJitter,
                AudioTrack.MODE_STREAM);
    }

    private void recordAndPlay()
    {
        final short[] lin = new short[1024];
        final int[] num = {0};
        audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
        int bufferSize = 0;
        while (true)
        {
            if (isRecording)
            {

                bufferSize++;
                Log.i("recording::","continue...");
                num[0] = audioRecord.read(lin, 0, 1024);
                audioTrack.write(lin, 0, num[0]);
           }
        }
    }

    private void startRecordAndPlay()
    {
                audioRecord.startRecording();
                audioTrack.play();
                isRecording = true;
    }

    private void stopRecordAndPlay()
    {
        audioRecord.stop();
        audioTrack.pause();
        audioTrack.release();
        isRecording = false;
    }

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
