### ISSUE TITLE
The footer is not at the bottom of the content

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#26]
![image](https://cloud.githubusercontent.com/assets/873212/12723380/13853684-c901-11e5-8b8b-5c9293c27455.png)

**Comment by Garbee** [comment]
This is because the pages are not constructed properly. The footer should be within the `.mdl-layout__content` block, not separate from it.

**Comment by dturner** [comment]
Thanks for the advice. Fixed now.
