### ISSUE TITLE
force java version 7 in module build.gradle files

### ISSUE THREAD

**Issue by ggfan** [googlesamples/android-audio-high-performance#4]
force java 7 compatibility in all module gradle files with at model { } level
    compileOptions.with {
        sourceCompatibility=JavaVersion.VERSION_1_7
        targetCompatibility=JavaVersion.VERSION_1_7
    }
this way if someone using java8 to compile it will still work

**Comment by Whiteseeker** [comment]
This is fixed by the pull request #12
