### ISSUE TITLE
AAudio sample buffer size Optimization

### ISSUE THREAD

**Issue by ggfan** [googlesamples/android-audio-high-performance#40]
Optional:

Currently sample gets the buffer size and frequency from Java side; the only used one is actually frequency.  The buffer size used to read/write AAudio's internal circular buffer is HARDCODED to framesPerBuffer(), which does not depend on Java side code ( but by all means it should be the same value though ). 

 Need re-visit this area and remove Java side parameter pulling to avoid confusion, of course, after a good cup of tea with @philburk

**Comment by ggfan** [comment]
some cleanup in the pull:  https://github.com/googlesamples/android-audio-high-performance/pull/43

**Comment by philburk** [comment]
The native AAudio framesPerBurst is more accurate than the Java AudioManager query because it is device specific. Depending on the device, they may not be the same.

**Comment by ggfan** [comment]
buffer size is cleaned out: no coming from Java side etc
