### ISSUE TITLE
[aaudio] On DP3 the input stream never reaches the STARTED state

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#58]
After starting an input stream, the state gets stuck in the STARTING state and does not ever reach STARTED. Despite this the stream can still be read from. 

Internal bug: 62781173

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
