### ISSUE TITLE
In hello-aaudio initial underruns should be ignored

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#63]
hello-aaudio has some latency tuning code which increases the buffer size if an underrun occurs. This is fine for normal use but sometimes when a stream is started a few underruns occur within the first few dataCallback calls. These underruns occur as part of the normal stream startup and should be ignored, rather than influencing the buffer size.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
