### ISSUE TITLE
[hello-aaudio] No audio output when switching from bluetooth to built-in speaker 

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#64]
Steps to repro: 

- Run hello-aaudio
- Connect a bluetooth audio device
- Select the bluetooth device from the drop down
- Tap the screen to verify that audio is produced through the bluetooth device 
- Choose 'built-in speaker' from the drop down
- Tap the screen 

Expected result

- Audio is produced from the built in speaker

Actual result

- No audio is produced

Tested on Pixel XL running O DP4

**Comment by dturner** [comment]
Also, latency figures aren't correct after device switch

**Comment by philburk** [comment]
Please also file this on the internal Buganizer so we can track it along with other issues.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
