### ISSUE TITLE
[aaudio/echo] Audio streams should be kept running to avoid startup latency

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#67]
This is important for samplers which may need to trigger a recording with the minimum possible latency from touch to record.

**Comment by dturner** [comment]
This will require an extra button to start/stop the input and output streams for the selected audio devices. Typical processes: 

**#1 start streams**
audio devices selected
"start streams" button pressed
input stream created and started
output stream created and started
flush input stream
0s (silence) written to output stream

**#2 start echo**
"start echo" button pressed
input stream read and written to output stream

**#3 stop echo**
"stop echo" button pressed
0s (silence) written to output stream

**#4 stop streams**
"stop streams" button pressed
input and output streams stopped and destroyed

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
