### ISSUE TITLE
[aaudio/hello-audio] MainActivity.getBufferSizeInBursts needs comment

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#70]
To more clearly explain what a burst is

**Comment by VandanaYanamachintala** [comment]
/* Here one Burst is equal to 192 frames.*/
private int getBufferSizeInBursts(){ 
   //This method will return the size of buffer from the buffer size spinner 
        @SuppressWarnings("unchecked") 
        HashMap<String,String> selectedOption = (HashMap<String,String>) 
                mBufferSizeSpinner.getSelectedItem(); 
     //The buffer size value which is selected from the buffersize spinner is stored in the HashMap selectedOption as key value pair.
        String valueKey = getString(R.string.buffer_size_value_key);
        //buffer_size_value_key is the name of string which is declared in the strings.xml. 

        // parseInt will throw a NumberFormatException if the string doesn't contain a valid integer 
        // representation. We don't need to worry about this because the values are derived from 
        // the BUFFER_SIZE_OPTIONS int array. 
        return Integer.parseInt(selectedOption.get(valueKey)); 
//From the HashMap selectedOption we are getting the value by using the key. Here both the //key and value are of type String. The value which is returned from the get fuction is given
// as input to the parseInt function which will convert the String to Integer value.
}

**Comment by dturner** [comment]
Thanks for your comments. I have updated the method docs.
