### ISSUE TITLE
Native error codes not reaching Java

### ISSUE THREAD

**Issue by philburk** [googlesamples/android-audio-high-performance#72]
It is quite possible for AAudio_openStream(), AAudioStream_requestStart() and other AAudio functions to return an error code. These codes should be passed all the way up to the Java code so that the user can be alerted.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
