### ISSUE TITLE
[SimpleSynth] Does not handle activity lifecycle events correctly

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#75]
Steps to repro: 
- Load app
- Switch test tone on
- Hit back button

Expected result: 
- Test tone stops

Actual result
- Test tone continues because audio engine isn't cleaned up

jni_bridge.cc needs methods to stop and destroy the audio engine.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
