### ISSUE TITLE
[aaudio/hello-audio] [Android Version 8.1.0] Wired Headset not working after running the hello-audio app

### ISSUE THREAD

**Issue by abhi-foss** [googlesamples/android-audio-high-performance#77]
Strange thing is happening on my device "Google Pixel - Android 8.1.0". Once I run this app, any other application on my device is not able to play audio via the headphones(even after closing the hello-audio app). The only way to fix this is to restart my device. Could you please confirm this behaviour ?

**Comment by ggfan** [comment]
tried on Pixel XL with my build of 8.1.0 ( it is pretty latest source code ), seems ok:  after hello-aaudio, I could go to "play music" to play some songs. 

may you put more details on the procedure? Like to see it first, thx.

**Comment by abhi-foss** [comment]
Following steps should help reproduce the issue :
1. Open the hello-audio app and keep the "Playback device" to "Auto select"
2. Touch the screen to play audio, the the audio will play fine via the device speaker.
3. Plugin the Headset, touch the screen again. this time audio will play via the connected headset.
4. Till this point we are all good, even the other app, "play music" works fine.
5. Now coming back to the hello-audio app, this time set the "playback device" as "Pixel built-in speaker". Touch the screen , Audio plays fine via the fine.
6. Now try switching the "playback device" to "Wired Headset". Touch the screen, audio will still play via the Speaker. Even the other apps, "play music" are in trouble now. Even if I close the 'hello-audio' . Restart is the only way out.

**Comment by dturner** [comment]
Please supply the exact Android build number you are testing on. This can be obtained through: Settings->About->Build number

**Comment by abhi-foss** [comment]
Its 'sailfish-userdebug 8.1.0 OPM1.170823.0014293864 dev-keys'

**Comment by dturner** [comment]
Please could you email me: donturner@google.com to discuss further.

**Comment by dturner** [comment]
Tested on Pixel XL running OPR6.170623.012 (Android O public release Aug 2017). I wasn't able to reproduce this behaviour, but was able to find a similar bug. I will file a separate issue for that.

**Comment by abhi-foss** [comment]
Thanks a lot.

**Comment by dturner** [comment]
Probably related to #78

**Comment by dturner** [comment]
Closing. @abhi-foss please follow up with me over email.
