### ISSUE TITLE
[aaudio/hello-aaudio] Changing playback device changes audio output for all apps

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#78]
hello-aaudio is able to change the audio output device for all apps. 

Device tested: Pixel XL running OPR6.170623.012 (Android O public release Aug 2017)

Steps to reproduce: 

- Insert headphones
- Load an app which plays audio (e.g. Play Music) or any webpage with sound (e.g. https://soundcloud.com/djbungle/bugdroidfest-menu-5min-loop) and start the audio
- Verify that audio is heard through headphones
- Load hello-aaudio app
- Change the "Playback device" to "built-in speaker"

Expected outcome:

- Music continues to play through headphones

Actual outcome: 

- Music plays through the built-in speaker

**Comment by dturner** [comment]
Filed internal bug id 66122712

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
