### ISSUE TITLE
existingFrameIndex in getTimestamp has a non consistent behavior

### ISSUE THREAD

**Issue by jbcolme** [googlesamples/android-audio-high-performance#80]
I'm getting a non consistent behavior using AAudioStream_getTimestamp.

After a first pause, flush, and restart, a quick call to AAudioStream_getTimestamp returns existingFrameIndex = 0. This was unexpected, because **the position and time passed back are monotonically increasing** (from the documentation)

After the second or any other pause, flush and restart, existingFrameIndex is not reset to 0 any more.

**Comment by dturner** [comment]
Thanks for reporting this. Which device and android build are you testing on please?

**Comment by jbcolme** [comment]
I'm using a Pixel, with Android 8 (build number OPR3.170623.007).

**Comment by dturner** [comment]
Internal issue id: 63918065
Fixed in: OPM1.170908.001

Thanks jbcolme.
