### ISSUE TITLE
[hello-oboe] Warning "Using custom NDK path (ANDROID_NDK is set):"

### ISSUE THREAD

**Issue by dturner** [googlesamples/android-audio-high-performance#97]
Getting the following warning during build: 

"Using custom NDK path (ANDROID_NDK is set):"

This is an issue with NDK 16.1 see: https://github.com/android-ndk/ndk/issues/599

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
