### ISSUE TITLE
No c++ compiler optimizations?

### ISSUE THREAD

**Issue by rpattabi** [googlesamples/android-audio-high-performance#98]
These samples meant for high performance audio are excellent. Considering the emphasis on high performance, why aren't there any compiler optimizations used in these samples?

Lazy guy like me, would take this as template to build our apps. So it is essential to include appropriate compiler optimizations as well.

This will also help me understand which of the plethora of the flags are appropriate in the context of android such as `-O3`

**Comment by dturner** [comment]
Great suggestion. 

I'm thinking we should have a Debug configuration which uses `-O0` and a Release configuration which uses `-Ofast`. I will update the CMakeLists.txt accordingly.

**Comment by ggfan** [comment]
probably check for the default compile options Gradle ( Android Studio ) is using for debug and release build; ndk samples are based on that assumption ( release build will use the best optimization for performance )

**Comment by rpattabi** [comment]
@ggfan Did a quick look. The c++ / ndk project generated by Android Studio 3.0.1 does not specify any optimization. So is the case with some of the google samples.

**Comment by ggfan** [comment]
thanks!  then we really need to add the best -O options inside CMakeLists.txt.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
